server:
  port: 9092

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/yzedu?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: yzedu
    password: yzedu

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.fstech.yzeduss.model
