server:
  port: 9091

spring:
  datasource:
    name: test
    url: jdbc:mysql://118.89.29.44:3306/yzedu?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: yzedu
    password: yzedu
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
  resources:
    static-locations: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.fstech.yzeduas.model